"""Build the Kaggle submission notebook for ARC-AGI-3 Misfit agent.

Generates `notebooks/submission.ipynb` with 4 cells following the proven
StochasticGoose contract pattern:

  Cell 0  offline pip install from the bundled arc_agi_3_wheels dir
  Cell 1  %%writefile /kaggle/working/my_agent.py — concatenated substrate
  Cell 2  KAGGLE_IS_COMPETITION_RERUN gateway bootstrap with slim __init__.py
  Cell 3  Non-rerun dummy submission.parquet for Phase A validation

Strategy for Cell 1: concatenate every src/misfit_agent/**/*.py file in
dependency order, strip relative `from .x import` lines (everything lives
in the same flat namespace inside my_agent.py), strip duplicate stdlib
imports, and wrap in `%%writefile`.

Run: `python scripts/build_notebook.py`
Output: notebooks/submission.ipynb
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).parent.parent
SRC = REPO / "src" / "misfit_agent"
NB_OUT = REPO / "notebooks" / "submission.ipynb"
META_OUT = REPO / "notebooks" / "kernel-metadata.json"


# Concatenation order — dependencies first.
MODULE_ORDER = [
    "config.py",
    "perceptor.py",
    "episode.py",
    "fingerprint.py",
    "resonance.py",
    "rules/no_op.py",
    "rules/translate.py",
    "world_model.py",
    "click_quantizer.py",
    "action_search.py",
    "misfit_agent.py",
]


# Patterns to strip from each module to make them concatenable into one file.
STRIP_LINE_PATTERNS = [
    r"^from\s+\.{1,2}[\w.]*\s+import\s+",  # relative imports
    r"^from\s+\.\s+import\s+",
    r"^\s*from\s+\.\s+import",
    r'^"""',                                # docstring fences (we'll keep module text)
    r"^__all__\s*=",                        # __all__ declarations
]


def _strip_relative_imports(text: str) -> str:
    """Remove `from .x import Y` lines — those names will be at top-level."""
    out_lines: list[str] = []
    in_docstring = False
    docstring_quote = None
    for line in text.splitlines():
        # Track triple-quoted module docstrings naively
        stripped = line.strip()
        if not in_docstring and (stripped.startswith('"""') or stripped.startswith("'''")):
            docstring_quote = stripped[:3]
            if stripped.count(docstring_quote) >= 2 and len(stripped) > 3:
                continue  # single-line docstring, skip
            in_docstring = True
            continue
        if in_docstring and stripped.endswith(docstring_quote or '"""'):
            in_docstring = False
            continue
        if in_docstring:
            continue
        if re.match(r"^from\s+\.{1,2}", line):
            continue
        if re.match(r"^__all__\s*=", line):
            continue
        out_lines.append(line)
    return "\n".join(out_lines)


def _dedup_stdlib_imports(text: str) -> str:
    """Collapse repeated stdlib imports across concatenated modules."""
    seen: set[str] = set()
    out: list[str] = []
    for line in text.splitlines():
        m = re.match(r"^(from\s+[\w.]+\s+import\s+.+|import\s+[\w.]+(?:\s+as\s+\w+)?)$", line.strip())
        if m:
            key = line.strip()
            if key in seen:
                continue
            seen.add(key)
        out.append(line)
    return "\n".join(out)


def _build_agent_module() -> str:
    """Concatenate the misfit substrate into a single self-contained module."""
    parts: list[str] = [
        '"""',
        "MisfitAgent — Tier-1 Spelke-priors ARC-AGI-3 agent (built notebook bundle).",
        "Generated by scripts/build_notebook.py — do not edit by hand.",
        "Source: https://github.com/AtomEons/arc-agi-3-misfit-agent",
        '"""',
        "",
        "# Standard library imports needed across the bundle",
        "from __future__ import annotations",
        "",
        "import json",
        "import math",
        "import os",
        "import pathlib",
        "import random",
        "import time",
        "from dataclasses import asdict, dataclass, field",
        "from typing import Any, Optional, Sequence",
        "",
        "import numpy as np",
        "",
        "# arcengine + framework — supplied by the eval container",
        "from arcengine import FrameData, GameAction, GameState",
        "from agents.agent import Agent",
        "",
    ]

    for rel_path in MODULE_ORDER:
        p = SRC / rel_path
        if not p.exists():
            raise FileNotFoundError(f"missing module: {rel_path}")
        text = p.read_text(encoding="utf-8")
        text = _strip_relative_imports(text)
        parts.append(f"\n# ============================================================")
        parts.append(f"# MODULE: {rel_path}")
        parts.append(f"# ============================================================\n")
        parts.append(text)

    # Drop duplicate stdlib imports across modules.
    body = "\n".join(parts)
    body = _dedup_stdlib_imports(body)

    # Provide a top-level alias so the framework's main.py finds our agent.
    body += "\n\n# Framework expects `MyAgent` to subclass Agent.\nMyAgent = Misfit\n"
    return body


def _build_notebook(agent_source: str) -> dict[str, Any]:
    """Construct the .ipynb JSON document."""
    def code_cell(source: str) -> dict[str, Any]:
        return {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": source.splitlines(keepends=True),
        }

    def md_cell(source: str) -> dict[str, Any]:
        return {
            "cell_type": "markdown",
            "metadata": {},
            "source": source.splitlines(keepends=True),
        }

    disclosure = (
        "# Misfit Agent — ARC-AGI-3 Tier-1 Submission\n"
        "\n"
        "**Tier-1 attestation:** this agent uses Spelke core knowledge object priors "
        "combined with a hand-authored typed rule grammar over those priors. "
        "**No pretrained model weights of any kind.** No language model in the "
        "inference path. **Apache-2.0 licensed.**\n"
        "\n"
        "Source: https://github.com/AtomEons/arc-agi-3-misfit-agent\n"
        "\n"
        "Mechanically enforced by `tests/test_tier1_attestation.py` — fails CI if any "
        "of `transformers`, `openai`, `anthropic`, `llama_cpp`, `huggingface_hub`, "
        "`sentence_transformers`, `langchain`, `langgraph`, `smolagents` are imported.\n"
    )

    cell0_install = (
        "# Cell 0 — offline wheel install from the bundled competition data.\n"
        "!pip install --no-index --find-links \\\n"
        "    /kaggle/input/competitions/arc-prize-2026-arc-agi-3/arc_agi_3_wheels \\\n"
        "    arc-agi python-dotenv\n"
    )

    cell1_writefile = "%%writefile /kaggle/working/my_agent.py\n" + agent_source

    cell2_rerun = (
        "# Cell 2 — KAGGLE_IS_COMPETITION_RERUN bootstrap (Phase B execution).\n"
        "import os\n"
        "\n"
        "if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):\n"
        "    # Wait for the eval gateway to come up.\n"
        "    !curl --fail --retry 999 --retry-all-errors --retry-delay 5 \\\n"
        "          --retry-max-time 600 http://gateway:8001/api/games\n"
        "\n"
        "    # Copy the framework to a writable location.\n"
        "    !cp -r /kaggle/input/competitions/arc-prize-2026-arc-agi-3/ARC-AGI-3-Agents \\\n"
        "           /kaggle/working/ARC-AGI-3-Agents\n"
        "\n"
        "    # Install our agent module into agents/templates/.\n"
        "    !cp /kaggle/working/my_agent.py \\\n"
        "        /kaggle/working/ARC-AGI-3-Agents/agents/templates/my_agent.py\n"
        "\n"
        "    # Slim __init__.py — skip langgraph/smolagents/openai whose deps\n"
        "    # are NOT in the offline wheel set. Eagerly importing them crashes\n"
        "    # the whole framework load before MyAgent gets registered.\n"
        "    with open('/kaggle/working/ARC-AGI-3-Agents/agents/__init__.py', 'w') as f:\n"
        "        f.write('''from typing import Type, cast\n"
        "from dotenv import load_dotenv\n"
        "from .agent import Agent, Playback\n"
        "from .swarm import Swarm\n"
        "from .templates.random_agent import Random\n"
        "from .templates.my_agent import MyAgent\n"
        "load_dotenv()\n"
        "AVAILABLE_AGENTS: dict[str, Type[Agent]] = {\"random\": Random, \"myagent\": MyAgent}\n"
        "''')\n"
        "\n"
        "    # .env — gateway endpoint per the rerun contract.\n"
        "    with open('/kaggle/working/ARC-AGI-3-Agents/.env', 'w') as f:\n"
        "        f.write('''SCHEME=http\n"
        "HOST=gateway\n"
        "PORT=8001\n"
        "ARC_API_KEY=test-key-123\n"
        "ARC_BASE_URL=http://gateway:8001/\n"
        "OPERATION_MODE=online\n"
        "ENVIRONMENTS_DIR=\n"
        "RECORDINGS_DIR=/kaggle/working/server_recording\n"
        "''')\n"
        "\n"
        "    # Run.\n"
        "    !cd /kaggle/working/ARC-AGI-3-Agents && \\\n"
        "        MPLBACKEND=agg \\\n"
        "        python main.py --agent myagent\n"
    )

    cell3_dummy = (
        "# Cell 3 — non-rerun dummy submission for Phase A validation.\n"
        "import os\n"
        "if not os.getenv('KAGGLE_IS_COMPETITION_RERUN'):\n"
        "    import pandas as pd\n"
        "    pd.DataFrame(\n"
        "        data=[['1_0', '1', True, 1]],\n"
        "        columns=['row_id', 'game_id', 'end_of_game', 'score']\n"
        "    ).to_parquet('/kaggle/working/submission.parquet', index=False)\n"
        "    print('Wrote dummy submission.parquet for Phase A.')\n"
    )

    return {
        "cells": [
            md_cell(disclosure),
            code_cell(cell0_install),
            code_cell(cell1_writefile),
            code_cell(cell2_rerun),
            code_cell(cell3_dummy),
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
            "kaggle": {
                "accelerator": "none",
                "dataSources": [],
                "isInternetEnabled": False,
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def _build_kernel_metadata(repo_user: str = "atommccree") -> dict[str, Any]:
    return {
        "id": f"{repo_user}/agi-in-a-video-shop-atom-eons-nostalgia",
        "title": "AGI in a Video Shop — AtomEons Nostalgia (Misfit Tier-1)",
        "code_file": "submission.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": "true",
        "enable_gpu": "false",
        "enable_internet": "false",
        "dataset_sources": [],
        "competition_sources": ["arc-prize-2026-arc-agi-3"],
        "kernel_sources": [],
    }


def main() -> None:
    NB_OUT.parent.mkdir(parents=True, exist_ok=True)
    agent_source = _build_agent_module()
    nb = _build_notebook(agent_source)
    NB_OUT.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    META_OUT.write_text(json.dumps(_build_kernel_metadata(), indent=2), encoding="utf-8")
    print(f"wrote {NB_OUT}  ({NB_OUT.stat().st_size:,} bytes)")
    print(f"wrote {META_OUT}")
    print(f"agent module: {len(agent_source.splitlines()):,} lines")


if __name__ == "__main__":
    main()
